users_password/users_pass_app/urls.py
from django.conf.urls import url
from users_pass_app import views

# template tagging

app_name = 'users_pass_app'

urlpatterns = [
  url('registeration/' , views.register, name = 'register'),
  url('user_login/', views.user_login, name= 'user_login'),

]

users_password/users_password/urls.py
from django.contrib import admin
from django.urls import path, include
from  users_pass_app import views
urlpatterns = [
    path('', views.index, name ='index'),
    path('admin/', admin.site.urls),
    path('register/', include('users_pass_app.urls')),
    path('logout/', views.user_logout, name ='logout'),
]

users_password/users_pass_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileData(models. Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE,)


    portfolio_data = models.URLField(blank =True)
    profile_image  = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

users_password/users_pass_app/forms.py
from django import forms
from django.contrib.auth.models import User
from users_pass_app.models import UserProfileData

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email' , 'password')
class UserProfileDataForm(forms. ModelForm):
    class Meta():
        model = UserProfileData
        fields = ('portfolio_data', 'profile_image')

users_password/users_pass_app/views.py
from django.shortcuts import render
from users_pass_app.forms import UserForm, UserProfileDataForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render (request, 'users_pass_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    regsitered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile = UserProfileDataForm(data=request.POST)

        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile.save(commit =False)
            profile.user = user


            if 'profile_image' in request.FILES:
                profile.profile_image = request.FILES['profile_image']
            profile.save()
            registered =True

        else:
            print(user_form.errors, user_profile.errors)
    else:
        user_form = UserForm()
        user_profile = UserProfileDataForm()

    return render(request, 'users_pass_app/registration.html' ,{'UserForm': user_form , 'UserProfileData' :user_profile, 'registered':register })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user =authenticate(username =username ,password= password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')

        else:
            print('someone tried to login and failed')
            print("username: {} and password {}".format(username, password))
            return HttpResponse('invalid lgin details supplied')
    else:
        return render(request, 'users_pass_app/login.html', {})

users_password/templates/users_pass_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title></title>
  </head>
  <body>
    <nav class =' navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'index'%}">Django</a></li>
          <li><a class= 'navbar-link' href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class= 'navbar-link' href="{% url 'users_pass_app:register'%}">Regsiter</a></li>

          {% if user.is_authenticated %}
          <li><a class='navbar-link' href="{% url 'logout'%}">Logout </a>
            {% else %}
            <li><a class='navbar-link' href="{% url 'users_pass_app:user_login'%}">Login </a>

          {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
    </div>

  </body>
</html>

users_password/templates/users_pass_app/index.html
{% extends 'users_pass_app/base.html'%}

{% block body_block %}
<h1>Welcome to the home page </h1>
<p>Please go to the registration page for registration </p>
{% endblock %}

users_password/templates/users_pass_app/login.html
{% extends 'users_pass_app/base.html'%}

{% block body_block%}
<div class="jumbotron">
  <h1> Login here</h1>
  <form class="" action="{% url 'users_pass_app:user_login'%}" method="POST">
    {% csrf_token%}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Username enter">
    <label for="password">Password</label>
    <input type="password" name="password" >
    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

users_password/templates/users_pass_app/registration.html
{% extends 'users_pass_app/base.html' %}
{% block body_block%}

<div class="jumbotron">
  {% if registered %}

  <h1>Thank you fro registration </h1>


  {% else%}
  <p>Fill out the registration form below</p>
  <h1> Registration form </h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{UserForm.as_p}}
    {{UserProfileData.as_p}}
    <input type="submit" name="" value="Submit">
  </form>




  {% endif %}



</div>





{%endblock%}